replicaCount: 1

global:
  storageClass: ""
  nodeSelector: {}
  affinity: {}
  tolerations: {}

metadata:
  labels:
    environment: dev

image:
  repository: itsolutionsdocker
  name: default-config
  tag: latest

volumes:
  bahmniConfig:
    capacity: "2Gi"

nodeSelector: {}
affinity: {}
tolerations: {}
